/* Autogenerated code, forces testlib to return exit codes for EJUDGE. */
#define EJUDGE

#include "testlib.h"
#include <iostream>

using namespace std;

const double EPS = 1E-3;
const char *NO_SOLUTION = "No solution";

int main(int argc, char **argv)
{
    registerTestlibCmd(argc, argv);

    string ja = ans.readString();
    string pa = ouf.readString();
    bool jhas = (ja != NO_SOLUTION);
    bool phas = (pa != NO_SOLUTION);
    if (!jhas && phas) {
        quitf(_wa, "There is no solution, but participant found it.");
    } else if (jhas && !phas) {
        quitf(_wa, "Solution exists, but participant didn't find it.");
    } else if (!jhas) {
        quitf(_ok, "No solution.");
    }
    ans.reset();    // Testlib thinks that I should not use this function.
    ouf.reset();
    double jl = ans.readDouble();
    double jr = ans.readDouble();
    double pl = ouf.readDouble();
    double pr = ouf.readDouble();
    if (abs(jl - pl) < EPS && abs(jr - pr) < EPS) {
        quitf(_ok, "Minimum length is %f, maximum length is %f.", jl, jr);
    } else {
        quitf(_wa, "Jury's [%f, %f] is not equal to participant's [%f, %f].", jl, jr, pl, pr);
    }
}
